apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: compose-example-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: compose-example-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compose-example-frontend
  template:
    metadata:
      labels:
        app: compose-example-frontend
    spec:
      containers:
        - name: compose-example-frontend
          image: pescador95/compose-example:reactservice
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
          env:
            - name: QUARKUS_BASEURL
              value: "http://backend-service:6000"
